from file_utils import read_csv

import pandas as pd
pd.set_option('display.max_rows', 250)

DEBUG = True

LOCAL_SITE_CODE = 'CHUM'
PATIENT_GLOBAL_SALT = '1fd5789d7ef4287fd8acfc765061e10eb3e7c093ff9150978695fb83692e4a87d55c4abf83c7ad9bcc3305ab03a4d28a5c404db6b84886c1665f949215e75a2b'
PATIENT_SITE_SALT = '243460170aec12b2cb4ce6e92d1293ebe8bbc83b4a860681ecfd4b653961f253fc3cb7ae833de5a4faca2d98ed9789e061e95aea7335901e6c84c7c05feee85f'
LIVE_SHEET_FILENAME = "/var/www/html/mchasse/covid19/data_all.csv"
CSV_DIRECTORY = "/data8/projets/Mila_covid19/output/covidb_full/csv"
BLOB_DIRECTORY = "/data8/projets/Mila_covid19/output/covidb_full/blob"
IMAGING_LIST_FILENAME = "/data8/projets/Mila_covid19/data/studies_to_extract.csv"
DICOM_MAP_FILENAME = "/data8/projets/Mila_covid19/data/patient_infos/dicom_id_map_v2.csv"
DICOM_DIRECTORY = "/data8/projets/Mila_covid19/data/covid_citadel_pacs_v2/covid_citadel_pacs_take2"
SQLITE_DIRECTORY = "/data8/projets/Mila_covid19/output/covidb_full/sqlite"
CODE_DIRECTORY = "/data8/projets/Mila_covid19/code/lmullie/git_Mila_covid19"

dicom_id_map_rows = read_csv(DICOM_MAP_FILENAME)
DICOM_PATIENT_ID_MAP = {}
DICOM_STUDY_ID_MAP = {}

for dicom_id_map_row in dicom_id_map_rows:
  if len(dicom_id_map_row) == 0: continue
  DICOM_PATIENT_ID_MAP[str(dicom_id_map_row[2])] = str(dicom_id_map_row[0])
  DICOM_STUDY_ID_MAP[str(dicom_id_map_row[2])] = str(dicom_id_map_row[1])

TABLE_COLUMNS = {

  'patient_data': [
    'patient_site_uid', 'patient_uid', 'pcr_sample_time', 
    'patient_site_code', 'patient_covid_status', 'patient_age', 
    'patient_sex', 'patient_vital_status', 'patient_was_admitted'
  ],

  'episode_data': [
    'patient_site_uid', 'episode_admission_uid', 
    'episode_unit_type', 'episode_start_time', 
    'episode_end_time', 'episode_description', 
    'episode_duration_hours'
  ],

  'diagnosis_data': [
    'patient_site_uid', 'episode_id', 'diagnosis_type',
    'diagnosis_name', 'diagnosis_icd_code', 'diagnosis_time'
  ],

  'drug_data': [
    'patient_site_uid', 'drug_name', 
    'drug_start_time', 'drug_end_time',
    'drug_frequency', 'drug_roa'
  ],

  'lab_data': [
    'patient_site_uid', 'lab_name', 'lab_sample_site', 
    'lab_sample_time', 'lab_result_time', 
    'lab_result_status', 'lab_result_units',
    'lab_result_string', 'lab_result_value'
  ],

  'observation_data': [
    'patient_site_uid', 'observation_name', 
    'observation_time', 'observation_value', #'observation_units'
  ],

  'pcr_data': [
    'patient_site_uid', 'pcr_name', 'pcr_sample_site', 'pcr_sample_time', 
    'pcr_result_time', 'pcr_result_value', 'pcr_result_status'
  ],

  'culture_data': [
    'patient_site_uid', 'culture_type', 'culture_specimen_type', 'culture_sample_time', 
    'culture_result_time', 'culture_growth_positive', 'culture_result_status'
  ],

  'imaging_data': [
    'patient_site_uid', 'imaging_accession_uid', 'imaging_modality', 'imaging_site',
    'imaging_acquisition_time'
  ],

  'slice_data': [
    'patient_site_uid', 'imaging_accession_uid', 'slice_study_instance_uid', 
    'slice_series_instance_uid', 'slice_data_uri', 'slice_view_position', 
    'slice_patient_position', 'slice_image_orientation', 'slice_image_position', 
    'slice_window_center', 'slice_window_width', 'slice_pixel_spacing', 
    'slice_thickness', 'slice_rows', 'slice_columns', 'slice_rescale_intercept', 
    'slice_rescale_slope'
  ]
}

CENSOR_COLUMNS = {
  'patient_data': [],
  'episode_data': ['episode_description'],
  'diagnosis_data': ['diagnosis_name', 'diagnosis_icd_code'],
  'drug_data': ['drug_name', 'drug_frequency', 'drug_roa'],
  'lab_data': ['lab_name', 'lab_sample_site'],
  'observation_data': ['observation_name'],
  'pcr_data': ['pcr_name', 'pcr_sample_site'],
  'culture_data': ['culture_type', 'culture_specimen_type'],
  'imaging_data': ['imaging_modality', 'imaging_site'],
  'slice_data': []
}

DRUG_SKIP_VALUES = [
  '*** rx a domicile', 
  'bcm à l\'urgence',
  '*attention: patient anticoagulé*',
  '*attention: catheter epidural en place*',
  'bilan comparatif des médicaments (bcm) au dossier.',
  '** protocole remap-cap (covid-19) **',
  '*bilan comparatif (bcm) à l\'admission*',
  '*attention : ecmo v-v en cours*',
  'dialyse: patient(e) dialysé(e)',
  '*** covid-19 cas suspecté ou confirmé ***',
  'vanconil -- patient(e) sous vancomycine i.v.' ,
  'warfarine: patient(e) sous warfarine.',
  '*attention : ecmo v-v en cours*',
  'covid-19 cas suspecté ou confirmé',
  'nitroglycerine retrait du ou des timbre(s)',
  '*attention: cvvh(df) en cours*',
  'solution pour dialyse',
  'eau sterile',
  'fournitures pharmacie',
  'détresse respiratoire',
  'detresse respiratoire',
  'polyvinylique alcool',
  'agitation importante',
  'convulsion',
  'rales bronchiques terminaux',
  'allergie au latex',
  'hors form: inscrire nom generique+ dosage',
  '*attention: catheter épidural en place*',
  'warfarine: ne pas donner ce jour',
  'nicotine timbre(s): retrait du ou des timbre(s)',
  'pharmacocinétique (pharmacie)',
  'hors form: inscrire nom générique+dosage',
  'diluant  sterile pour  injection (epoprostenol)',
  'vehicule-magistrale'
]

DRUG_NAME_MAP = {
  'acide acetylsalicylique': 'aspirin',
  'dextrose 5% sans pvc': 'dextrose 5%',
  'bupivacaine 0,0625% dans nacl 0,9%': 'bupivacaine 0,0625%',
  'bupivacaine 0,1% dans nacl 0,9%': 'bupivacaine 0.1%',
  'bupivacaine 0,125% dans nacl 0,9%': 'bupivacaine 0.125%',
  'bupivacaine 0,0625%+fentanyl 2 mcg/ml dans nacl 0,9%': 'bupivacaine 0.0625% + fentanyl 2 mcg/ml',
  'bupivacaine 0,1%+fentanyl 2 mcg/ml dans nacl 0,9%': 'bupivacaine 0.1% + fentanyl 2 mcg/ml',
  'sodium chlorure 0,9% sans pvc': 'sodium chloride 0.9%',
  'sodium chlorure 0,9%': 'sodium chloride 0.9%',
  'hydromorphone ds nacl 0.9% (acp)': 'hydromorphone',
  'morphine ds nacl 0.9% (acp)': 'morphine',
  'midazolam inj 1 mg/ml (100 ml)': 'midazolam',
  'hydrocortisone *solu-cortef*': 'hydrocortisone',
  'methylprednisolone *solu-medrol*': 'methylprednisolone',
  'clotrimazole 0,5%/hydrocortisone 0,5%': 'clotrimazole 0.5%/hydrocortisone 0.5%',
  'filgrastim ** grastofil **': 'filgrastim',
  'filgrastim ** neupogen **': 'filgrastim',
  'mofetil mycophenolate *cellcept*': 'mycophenolate mofetil',
  'mycophenolate sodique *myfortic*': 'mycophenolate sodium',
  'cyclosporine *neoral*': 'cyclosporine',
  'fer gluconate *ferrlecit*': 'fer gluconate',
  'methylprednisolone *depo-medrol*': 'methylprednisolone',
  'nitroprussiate ** nipride **': 'nitroprussiate',
  'lenalidomide caps 5 mg *ensaposs*': 'lenalidomide',
  'sevelamer carbonate pd.orale 0.8g sachets **': 'sevelamer carbonate',
  'infliximab ** remicade **': 'infliximab',
  'infliximab ** inflectra **': 'infliximab',
  'norepinephrine inj 8mg/ns minisac (258ml) *si': 'norepinephrine',
  'tiotropium caps.inh 18 mcg  *ensaposs*': 'tiotropium',
  'tiotropium inh   *ensaposs*': 'tiotropium',
  'indacaterol caps.inh 75 mcg *ensaposs*': 'indacaterol',
  'indacaterol inh *ensaposs*': 'indacaterol',
  'formoterol/mometasone inh 5+200mcg/inh*zenhal': 'formoterol/mometasone',
  'glycopyrronium bromure caps.inh 50 mcg   *ens': 'glycopyrronium bromide',
  'glycopyrronium bromure': 'glycopyrronium bromide',
  'salbutamol inh 100 mcg/dose *ensaposs*': 'salbutamol',
  'salmeterol/fluticasone inh 25+125 mcg/inh *en': 'salmeterol/fluticasone',
  'formoterol inh 12 mcg/inh *ensaposs*': 'formoterol',
  'lenalidomide caps 25 mg *ensaposs*': 'lenalidomide',
  'vemlidy (tenofovir alafenamide)': 'tenofovir alafenamide',
  'viread (tenofovir disoproxil)': 'tenofovir disoproxil',
  'phytonadione (vit k)': 'vitamin k',
  'ergocalciferol (vitamine d)': 'vitamin d',
  'cholecalciferol (vitamine d3)': 'vitamin d3',
  'tocopheryle  (vit e)': 'vitamin e',
  'thiamine (vit b1)': 'vitamin b1',
  'pyridoxine (vitamine b6)': 'vitamin b6',
  'ascorbique acide (vit. c)': 'vitamin c',
  'phenylephrine inj 50 mcg/ml (seringue)': 'phenylephrine',
  'etomidate (p.a.s.)': 'etomidate',
  'prasugrel (p.a.s.)': 'prasugrel',
  'rifampine (p.a.s.)': 'rifampin',
  'nicardipine (p.a.s)': 'nicardipine',
  'foscarnet (p.a.s.)': 'foscarnet',
  'clevidipine (p.a.s)': 'clevidipine',
  'doxycycline (p.a.s.)': 'doxycyline',
  '#lopinavir+ritonavir co 80+20 mg/ml (160 ml': 'lopinavir+ritonavir',
  '#lopinavir+ritonavir co 200+50 mg': 'lopinavir/ritonavir',
  'novorapid (aspart)': 'insulin aspart',
  'humalog (lispro)': 'insulin lispro',
  'apidra (glulisine)': 'insulin glulisine',
  'tresiba (degludec)': 'insulin degludec',
  'lantus (glargine)': 'insulin glargine',
  'toujeo (glargine)': 'insulin glargine',
  'basaglar (glargine)': 'insulin glargine',
  'levemir (detemir)': 'insulin detemir',
  'novomix (aspart+aspart-protamine)': 'insulin aspart/aspart-protamine',
  'humalog mix 25 (lispro+lispro-protamine)': 'insulin lispro/lispro-protamine',
  'folinique acide (leucovorin)': 'folinic acid',
  'dextromethorphane (sans sucre)': 'dextromethorphan',
  'lipides (smoflipid)': 'lipid injectable emulsion',
  'lipides (intralipid)': 'lipid injectable emulsion',
  'zoledronique acide (aclasta)': 'zoledronic acid',
  'zoledronate (zometa)': 'zoledronate',
  'stalevo 75/18,75/200 mg': 'levodopa/carbidopa/entacapone 75/18.75/200 mg',
  'stalevo 150/37,5/200 mg': 'levodopa/carbidopa/entacapone 150/37.5/200 mg',
  'tuberculine derivee (ppd)': 'tuberculin',
  'amphetamines (sels mixtes)': 'amphetamines (mixed salts)',
  'atgam 0,05 mg/ml (5 ml)': 'anti-thymocyte globulin',
  'oligo-elements (cr/cu/ma/zn/se/i)': 'oligo-elements'
}

DRUG_ROUTE_MAP = {
  'sous-cutané': 'sc',
  'sous-cutané:': 'sc',
  'dans les oreilles': 'otic',
  'dans oreille droite': 'otic',
  'dans oreille gauche': 'otic',
  'ophthalmique': 'i-ocul',
  'dans les yeux': 'i-ocul',
  'dans l\'oeil droit': 'i-ocul',
  'dans l\'oeil gauche': 'i-ocul',
  'per os': 'po',
  'per os ou sublingual': 'po/sl',
  'via jéjunostomie': 'ng',
  'via gastrostomie': 'ng',
  'via tube nasogastro.': 'ng',
  'via levin': 'ng',
  'rince-bouche': 'buccal',
  'en gargarisme': 'buccal',
  'buccale': 'buccal',
  'irr.nasale': 'nasal',
  'intra-pleurale': 'i-pleural',
  'dans une narine': 'nasal',
  'dans les narines': 'nasal',
  'nasale': 'nasal',
  'infiltration': 'infil',
  'transdermique': 't-dermal',
  'intra-dermique': 'i-dermal',
  'en injection locale': 'i-epidermal',
  'cathéter': 'iv',
  'i.v.': 'iv',
  'mini-perfuseur': 'iv',
  'i.v. perfusion': 'iv',
  'i.v. tubulure': 'iv',
  'i.v. soluté': 'iv',
  'i.v. / s.c.': 'iv/sc',
  'par voie centrale': 'iv',
  'i.m.': 'im',
  'i.m./i.v./s.c.': 'im/iv/sc',
  'i.m. / s.c.': 'im/sc',
  'i.m. / i.v.': 'im/iv',
  'perfusion s.c.': 'sc',
  'en appl. locale': 'topic',
  'en compresses': 'topic',
  'topique': 'topic',
  'intra-rectal': 'rectal',
  'voir directives': 'unknown',
  'transdermale': 't-dermal',
  'transmucosale': 't-mucos',
  'épidurale': 'epidur',
  'intra-rachidienne': 'i-spinal',
  'orale(s)': 'po',
  'sublinguale': 'sl',
  'sous la langue': 'sl',
  'nébulisation orale': 'respir',
  'en inhalation orale': 'respir',
  'en aérosol': 'respir',
  'vaginale': 'vagin',
  'dans le dialysat': 'hemo',
}

SIURG_OBSERVATION_NAMES = [
  'temperature', 'pouls', 'tension_systol', 
  'tension_diastol', 'sat_o2', 'rythme_resp'
]

LAB_PENDING_FLAGS = [
  'En attente'
]

LAB_CANCELLED_FLAGS = [
  'Test annulé', 'Test Annulé', 'ANN', 
  'ann', 'annulé', 'ANNULE', 'ANNULÉ',
  'test annulé', 'Annulé', 'ANNULe', 'annule'
]

LAB_SKIP_VALUES = [
  '.', '..', ',',
  '*00.0', '9*', '*9', 
  'att. hémolyse', 
  'pré-collecte',
  'durée gross. (sem.)', 
  'g10_sorgho d\'alep', 
  'volume 24 heures',
  'coll. cell. souches',
  'gb cell.souches',
  'hb cell.souches',
  'plt cell.souches',
  'cell.mononucléées (c.s.)',
  'cell.polynucléées (c.s.)',
  'gb cell.souches',
  'hb cell.souches',
  'plt cell.souches',
  'cell.mononucléées (c.s.)',
  'cell.polynucléées (c.s.)',
  'hb semi-quantitatif',
  'po2 sg cord.tc',
  'pco2 sg cord.tc',
  'sat o2 cordon art',
  'hco3 act.sg c.',
  'po2 sg cord.v.tc',
  'pco2 sg cord.tc',
  'sat o2 cordon vein',
  'hco3 act.sg c.v.',
  'bil.t.cordon',
  'ex.base sg cord.',
  'ex.base sg c. v.'
]

LAB_NAMES_MAP = {
  '% éosino.urin.': 'urinary_eosinophil_percent', 
  '1-25(oh)2-vit.d': '1_25_oh_vitamin_d', 
  '25(oh)-vit. d': '25_oh_vitamin_d', 
  'a-1-antitryps. %': 'alpha1_antitrypsin_percent', 
  'a-1-glycoprot. %': 'alpha1_glycoprotein_percent', 
  'a-1-glycoprot., élec': 'alpha1_glycoprotein', #
  'a.foetoprotéine': 'alpha_fetoprotein', 
  'a.lactique (rés.prélim.)': 'lactic_acid', 
  'a1 antitrypsine': 'alpha_1_antitrypsin', 
  'a1-antitrypsine, élec': 'alpha1_antitrypsin', 
  'a2-macroglob. %': 'alpha2_macroglobulin_percent', 
  'a2-macroglob., élec': 'alpha2_macroglobulin', 
  'acth': 'adrenocorticotropic_hormone', 
  'alt': 'alanine_aminotransferase', 
  'arn vih-1': 'hiv1_rna', 
  'arn vih-1/log': 'hiv1_rna_log', 
  'ast': 'ast', 
  'ac fac.intrins.': 'anti_intrinsic_factor', 
  'ac.anti thyroglobuline': 'anti_thyroglobulin',
  'ac. valproïque': 'valproic_acid', 
  'acide folique': 'folic_acid', 
  'acide lac.art. ser.': 'arterial_lactic_acid', 
  'acide lactique': 'lactic_acid', 
  'acide urique': 'uric_acid', 
  'acides biliaires': 'biliary_acids', 
  'act. anti-xa bpm': 'anti_xa_bpm_activity', 
  'act. anti-xa rivaro.': 'anti_xa_rivaro_activity', 
  'acétaminophène': 'acetaminophen', 
  'ag carcino emb.': 'carcinoembryonic_antigen', 
  'albumine': 'albumin', 
  'albumine %': 'albumin_percent', 
  'albumine, liq.': 'albumin', 
  'albumine, urine': 'albumin', 
  'albumine, élec.': 'albumin', 
  'albumine-u 24 h': 'albumin', 
  'albumine-u mict.': 'albumin', 
  'ammoniac': 'ammonia', 
  'amylase, liq.': 'amylase', 
  'anti dna unité': 'anti_dna', 
  'anti héparine': 'anti_heparin', 
  'anti jo-1': 'anti_jo1', 
  'anti-ccp igg': 'anti_ccp_igg', 
  'anti-hbs unités': 'anti_hbs', 
  'anti-hcv s/co': 'anti_hcv', 
  'anti-microsomiaux (anti-tpo)': 'anti_tpo)', 
  'anti-récep.tsh': 'anti_tshr', 
  'anti-thyroglobuline (sér.)': 'anti_thyroglobulin', 
  'anti-transglutaminase (iga)': 'anti_transglutaminase', 
  'anticardio.igg': 'anticardiolipin_igg', 
  'anticardio.igm': 'anticardiolipin_igm', 
  'anticorps anti-gad': 'anti_gad', 
  'antigène prost.': 'prostate_specific_antigen', 
  'b-hcg (quant.)': 'beta_hcg', 
  'b-hcg résultat prélim.': 'beta_hcg',
  'b2 microglob.': 'beta2_microglobulin', 
  'b2-glycopro.igg': 'beta2_glycoprotein', 
  'baso #': 'basophil_count', 
  'baso # (man)': 'basophil_count', 
  'benzo. (urine)*': 'benzodiazepines', 
  'benzo. totales*': 'benzodiazepines', 
  'bilirubine dir.': 'direct_bilirubin', 
  'bilirubine ind.': 'indirect_bilirubin', 
  'bilirubine tot.': 'total_bilirubin', 
  'bilirubine directe, liquide': 'direct_bilirubin', 
  'bilirubine, liq.': 'total_bilirubin', 
  'blaste # (man)': 'blast_count', 
  'c télopeptide s': 'c_telopeptide', 
  'c-anca pr3 val.': 'c_anca_pr3', 
  'c3': 'c3', 
  'c3/iga': 'c3/iga', 
  'c3/iga %': 'c3/iga %', 
  'c4': 'c4', 
  'ca 125': 'cancer_antigen_125', 
  'ca 15-3': 'cancer_antigen_15_3', 
  'ca 19-9': 'cancer_antigen_19_9', 
  'cd16+56 absolu': 'cd16_56_count', 
  'cd19 absolu': 'cd19_count', 
  'cd3 absolu': 'cd3_count', 
  'cd4 absolu': 'cd4_count', 
  'cd8 absolu': 'cd8_count', 
  'cenp-b': 'cenp_b', 
  'cgmh': 'mean_corpuscular_hemoglobin_concentration',
  'ck (au)': 'creatine_kinase', 
  'ckmb masse': 'ck_mb', 
  'cmv (charge virale)': 'cmv_rna', 
  'cmv igg unités': 'cmv_igg', 
  'cmv igm index': 'cmv_igm', 
  'co2 total': 'bicarbonate', 
  'ca ion.(ph:7.4).': 'ionized_calcium_ph74', 
  'ca ionisé act.': 'ionized_calcium', 
  'calcitonine': 'calcitonin', 
  'calcium, mict.': 'calcium',
  'calcium total': 'total_calcium', 
  'calcium total corrigé': 'corrected_total_calcium', 
  'carbamazépine': 'carbamazepine', 
  'carboxyhb vein': 'carboxyhemoglobin', 
  'chlorure': 'chloride', 
  'chlorure (lcr)': 'chloride', 
  'chlorure veineux': 'chloride', 
  'chlorure, liq.': 'chloride', 
  'chlorure, mict.': 'chloride', 
  'cholestérol': 'cholesterol', 
  'cl seringue': 'chloride', 
  'cortisol (s)': 'cortisol', 
  'créatinine': 'creatinine', 
  'créatinine 24 h': 'creatinine', 
  'créatinine urine': 'creatinine', 
  'créatinine, liq.': 'creatinine', 
  'créatinine,mict.': 'creatinine', 
  'cryoglobuline': 'cryoglobulin',
  'cyclo.2 h post-d': 'cyclosporin_2h_post_dose', 
  'cyclos. pré-dose': 'cyclosporin_pre_dose', 
  'céruloplasmine': 'ceruloplasmin', 
  'd-dimère': 'd_dimer', 
  'digoxine': 'digoxin', 
  'dopamine': 'dopamine', 
  'dopamine 24 h': 'dopamine_24h', 
  'décompte cell.tot. lba': 'cell_count', 
  'ebv-vca igm ind': 'anti_ebv_vca_igm', 
  'ebna1 igg index': 'anti_ebna1_igg', 
  'excès de base': 'base_excess', 
  'excès de base (v)': 'base_excess', 
  'ethyl glucuron.': 'ethyl_glucuronide',
  'épinéphrine': 'epinephrine',
  'épinéphrine 24h': 'epinephrine_24h',
  'f.rhumatoïde': 'rheumatoid_factor', 
  'fsh': 'follicle_stimulating_hormone', 
  'facteur ii': 'factor_ii', 
  'facteur v': 'factor_v', 
  'facteur vii': 'factor_vii', 
  'facteur viii': 'factor_viii', 
  'facteur ix': 'factor_ix', 
  'fer sérique': 'serum_iron', 
  'ferritine': 'ferritin', 
  'fibrinogène': 'fibrinogen', 
  'fibrinogène imm.': 'fibrinogen', 
  'gb': 'white_blood_cell_count', 
  'ggt': 'gamma_glutamyl_transferase', 
  'gr': 'red_blood_cell_count', 
  'gamma glob. %': 'gamma_globulin_percent', 
  'gamma globuline, élec': 'gamma_globulin', 
  'gap anion.': 'anion_gap', 
  'gl.bl l.périt': 'white_blood_cell_count',
  'gl.blancs l.asc': 'white_blood_cell_count', 
  'gl.blancs l.bio': 'white_blood_cell_count', 
  'gl.blancs l.ple': 'white_blood_cell_count', 
  'gl.blancs lcr': 'white_blood_cell_count', 
  'gl.rou. l.périt': 'red_blood_cell_count',
  'gl.rou. l.bio': 'red_blood_cell_count', 
  'gl.rou. lcr': 'red_blood_cell_count', 
  'gl.rou.l.asc': 'red_blood_cell_count', 
  'globulines': 'globulins', 
  'glucose': 'glucose', 
  'glucose (lcr)': 'glucose', 
  'glucose ac': 'glucose', 
  'glucose adbd': 'glucose', 
  'glucose, liq.': 'glucose', 
  'hbv dna': 'hbv_dna', 
  'hco3 actuel': 'bicarbonate', 
  'hco3 actuel (v)': 'bicarbonate', 
  'hdl-cholestérol': 'hdl_cholesterol', 
  'hsv-1 index': 'anti_hsv1_igg', 
  'hsv-2 index': 'anti_hsv2_igg', 
  'haptoglobine': 'haptoglobin', 
  'haptoglobine %': 'haptoglobin_percent', 
  'haptoglobine, élec.': 'haptoglobin', 
  'hb': 'hemoglobin', 
  'hb l.bio': 'hemoglobin', 
  'homocystéine': 'homocysteine', 
  'iga': 'iga', 
  'ige': 'ige', 
  'igg': 'igg', 
  'igm': 'igm', 
  'indice alb/créa': 'albumin_creatinine_ratio', 
  'k seringue': 'potassium', 
  'k, selles': 'potassium', 
  'kappa libre': 'free_kappa', 
  'lactate sg tot': 'total_lactate',
  'ld': 'lactate_dehydrogenase', 
  'ld, liq.': 'lactate_dehydrogenase', 
  'ldl-c (calc)': 'ldl_cholesterol', 
  'lh': 'luteinizing_hormone', 
  'lithium': 'lithium', 
  'lambda libre': 'free_lambda', 
  'lipase.': 'lipase', 
  'lympho #': 'lymphocyte_count', 
  'lympho # (man)': 'lymphocyte_count', 
  'lympho % lba': 'lymphocyte_count', 
  'magnésium': 'magnesium', 
  'memb. basale glom.': 'anti_gbm_igg', 
  'mono #': 'monocyte_count', 
  'mono # (man)': 'monocyte_count', 
  'mono-macro lba': 'mono_macro_count', 
  'myélocyte # (man)': 'myelocyte_count', 
  'métamyélocyte # (man)': 'metamyelocyte_count', 
  'métanéphrine': 'metanephrine', 
  'métan. 24 h': 'metanephrine_24h', 
  'métanéphrine libre': 'free_metanephrine', 
  'méthémoglob vein': 'methemoglobin', 
  'nt pro-bnp': 'nt_pro_bnp', 
  'na seringue': 'sodium', 
  'nb cellules/ml': 'total_cell_count', 
  'neutro #': 'neutrophil_count', 
  'neutro # (man)': 'neutrophil_count', 
  'neutro % lba': 'neutrophil_count', 
  'non-hdl cholest': 'non_hdl_cholesterol', 
  'norépinéphrine': 'norepinephrine',
  'norépiné. 24 h': 'norepinephrine_24h',
  'normétanéphrine': 'normetanephrine', 
  'normétan. 24 h': 'normetanephrine_24h', 
  'normétanéphrine libre': 'free_normetanephrine', 
  'osm.calc.selles': 'osmolality', 
  'osmo. (plasma)': 'osmolality', 
  'osmolalité calculée': 'osmolality', 
  'osmolalité urine': 'osmolality', 
  'ostéocalcine': 'osteocalcin',
  'oxycodone qual. (mict.)': 'oxycodone', 
  'p-anca mpo val.': 'p_anca_mpo', 
  'plt': 'platelet_count', 
  'plt sur lame': 'manual_platelet_count', 
  'pth intacte': 'intact_pth', 
  'ptt-la': 'ptt_lupus_anticoagulant', 
  'ptt-la (1:1)': 'ptt_lupus_anticoagulant_11', 
  'parvo b19 igg index': 'anti_parvo_b19_igg', 
  'peptide-c': 'c_peptide', 
  'phosphatase alc.': 'alkaline_phosphatase', 
  'phosphore': 'phosphate', 
  'phénobarbital': 'phenobarbital', 
  'phénytoïne': 'phenytoin', 
  'pic mono. 1': 'monoclonal_peak', 
  'pic mono. 1 %': 'monoclonal_peak_percent', 
  'potassium': 'potassium', 
  'potassium veineux': 'potassium', 
  'potassium, mict.': 'potassium', 
  'procalcitonine': 'procalcitonin', 
  'prolactine': 'prolactin', 
  'promyélocyte # (man)': 'promyelocyte_count', 
  'prot u/créat u': 'protein_creatinine_ratio', 
  'protéine c réac.': 'c_reactive_protein', 
  'protéines (lcr)': 'total_protein', 
  'protéines 24 h': 'total_protein', 
  'protéines tot.mict.': 'total_protein', 
  'protéines totales': 'total_protein', 
  'protéines urine': 'total_protein', 
  'protéines, liq.': 'total_protein', 
  'prot.s libre ag': 'free_prostate_specific_antigen',
  'rnp': 'anti_rnp_igg', 
  'rvvt 1:1': 'rvvt_11', 
  'rvvt confirme': 'rvvt_confirmation', 
  'rvvt dépistage': 'rvvt_screen', 
  'rénine': 'renin',
  'rétic#': 'reticulocyte_count', 
  'rubéole igg val': 'anti_rubella_igg',
  'scl70': 'anti_scl70_igg', 
  'shbg': 'sex_hormone_binding_globulin', 
  'sm': 'sm', 
  'ssa': 'anti_ssa', 
  'ssb': 'anti_ssb', 
  'salicylates': 'salicylates', 
  'sat o2 art': 'o2_sat', 
  'sat o2 vein': 'o2_sat', 
  'sodium': 'sodium', 
  'sodium veineux': 'sodium', 
  'sodium, mict.': 'sodium', 
  'sodium, selles': 'sodium', 
  'stab # (man)': 'stab_count', 
  'staclot-la: buffer': 'staclot_la_buffer', 
  'staclot-la: phospho': 'staclot_la_phospho', 
  't.céph.(1:1)': 'partial_thromboplastin_time_11', 
  't.céphaline sec': 'partial_thromboplastin_time', 
  't.thrombine': 'thrombin_time', 
  't3 libre': 'free_t3', 
  't4 libre': 'free_t4', 
  'tgmh': 'mean_corpuscular_hemoglobin', 
  'tsh': 'thyroid_stimulating_hormone', 
  'tacrolimus': 'tacrolimus', 
  'testostérone t': 'total_testosterone', 
  'thyroglobuline': 'thyroglobulin', 
  'toxo igm(index)': 'anti_toxoplasma_igm', 
  'toxoplasma igg': 'anti_toxoplasma_igg', 
  'transferrine': 'transferrin', 
  'transferrine %': 'transferrine_saturation', 
  'transferrine, élec.': 'transferrin', 
  'transthyrétine': 'transthyretin', 
  'triglycérides': 'triglycerides', 
  'triglycérides, liq.': 'triglycerides', 
  'tropt hs sous réserve': 'hs_troponin_t', 
  'troponine-t hs': 'hs_troponin_t', 
  'urée': 'urea', 
  'urée, mict.': 'urea', 
  'vgm': 'mean_corpuscular_volume', 
  'vpm': 'mean_platelet_volume', 
  'vs': 'erythrocyte_sedimentation_rate', 
  'vanco post dose': 'vancomycin_post_dose', 
  'vanco pré dose': 'vancomycin_pre_dose', 
  'vancomycine': 'vancomycin', 
  'vitamine a': 'vitamin_a', 
  'vitamine b12': 'vitamin_b12', 
  'vitamine e': 'vitamin_e', 
  'voriconazole': 'voriconazole', 
  'pco2 tc': 'pco2', 
  'pco2 veineux tc': 'pco2', 
  'po2 tc': 'po2', 
  'po2 veineux tc': 'po2', 
  'éosino #': 'eosinophil_count', 
  'éosino # (man)': 'manual_eosinophil_count', 
  'éosino lba %': 'eosinophil_percent', 
  'éthanol': 'ethanol',
  'éthanol (ur)': 'ethanol',
  'aldostérone sér.': 'aldosterone',
  'phosphore, mict.': 'phosphate',
  'arn-hcv/copies': 'hcv_rna',
  'arn-hcv/log': 'hcv_rna_log',
  'magnésium, mict': 'magnesium',
  'dhea-so4': 'dhea_so4',
  'gl.rou. l.ple': 'red_blood_cell_count',
  'carboxyhb art': 'carboxyhemoglobin',
  'méthémoglob art': 'methemoglobin',
  'gl.rou. l.ple': 'red_blood_cell_count',
  'fructosamine': 'fructosamine',
  'fructo/prot': 'fructosamine_prot',
  'm3_asper.fumig.': 'aspergillus_antibodies',
  'lamotrigine': 'lamotrigine',
  'atiii fonc.': 'antithrombin_iii',
  'hbs ag quantitatif': 'hbv_sag',
  'varicelle igg index': 'anti_vzv_igg',
  'hb semi-quantitatif': 'free_hemogloin',
  'hb plasmat. dosage': 'plasma_hemoglobin',
  'act.anti-xa hép.std': 'anti_xa',
  'hb semi-quantitatif': 'hemoglobin_semiquant',
  'tobra post dose': 'tobramycin_post_dose',
  'po2 art ecmo': 'po2',
  'pco2 art ecmo': 'pco2',
  'sat o2 art ecmo': 'arterial_o2_sat',
  'excès base art ecmo': 'base_excess',
  'excès base vein ecmo': 'base_excess',
  'po2 art ecmo': 'po2',
  'pco2 art ecmo': 'pco2',
  'sat o2 art ecmo': 'o2_sat',
  'hco3 art ecmo': 'bicarbonate',
  'pco2 vein ecmo': 'pco2',
  'po2 vein ecmo': 'po2',
  'sat o2 vein ecmo': 'o2_sat',
  'hco3 vein ecmo': 'bicarbonate',
  'g6pd quantit.': 'g6pd_quantitative',
  '6pgd quantit.': 'g6pd_quantitative',
  'enz.conversion': 'angiotensin_converting_enzyme',
  'éthanol (p)': 'ethanol',
  'amylase, mict.': 'amylase'
}

NP_TO_FIO2_MAP = {
  '0.5': '22',
  '1.0': '24',
  '1.5': '26',
  '2.0': '28',
  '2.5': '30',
  '3.0': '32',
  '3.5': '34',
  '4.0': '36',
  '4.5': '38', 
  '5.0': '40',
  '5.5': '42',
  '6.0': '44',
  '6.5': '46',
  '7.0': '48',
  '7.5': '50',
  '8.0': '52',
  '8.5': '54',
  '9.0': '56',
  '9.5': '58',
  '10.0': '60'
}

UNIT_TYPE_MAP = {
  '12S': 'inpatient_ward', #'Unité 12 Sud',  
  '17N': 'inpatient_ward', #'Unité 17 Nord', 
  '13N': 'inpatient_ward', #'Unité 13 Nord', 
  '10N': 'intensive_care_unit', #Unité des soins intensifs (NORD)', 
  'CCJ1': 'day_surgery_unit', #'Chirurgie du même jour (1) CHUM', 
  '14S': 'inpatient_ward', #'Unité 14 Sud', 
  '01CJ': 'day_surgery_unit', #"Unité de chirurgie d'un jour Ophtalmologie", 
  '11NT': 'inpatient_ward', #'Unité  de médecine des toxicomanies', 
  '15N': 'inpatient_ward', #'Unité 15 Nord', 
  '11NI': 'high_dependency_unit', #'Unité des soins intensifs de psychiatrie', 
  '15S': 'inpatient_ward', #'Unité 15 Sud', 
  '14N': 'inpatient_ward', #'Unité 14 Nord', 
  '13S': 'inpatient_ward', #'Unité 13 Sud', 
  '17SM': 'high_dependency_unit', #'Unité 17 Sud- S. intermédiaires', 
   #'CBI ': 'Unité fantôme', 
  '09SA': 'inpatient_ward', #'Unité de naissance', 
  '11NY': 'inpatient_ward', #'Unité de psychiatrie - toxico', 
  'CHEM': 'cardiac_catheterization_lab', #'Unité Hémodynamie  CHUM', 
  '13NM': 'high_dependency_unit', #'Unité 13 Nord- S.intermédiaires', 
  '18S': 'inpatient_ward', #'Unité 18 Sud', 
  '19S': 'inpatient_ward', #'Unité 19 Sud', 
  '09S': 'inpatient_ward', #'Unité Mère-enfant', 
  '17S': 'inpatient_ward', #Unité 17 Sud', 
  '16S': 'inpatient_ward', #'Unité 16 Sud', 
  'CCJ2': 'day_surgery_unit', #'Chirurgie du même jour (2) CHUM', 
  '11S': 'inpatient_ward', #'Unité 11 Sud', 
  '19': 'inpatient_ward', #'Unité 19 Nord', 
  '19N': 'inpatient_ward', #'Unité 19 Nord', 
  '10S': 'intensive_care_unit', #'Unité des soins intensifs (SUD)', 
  '08S': 'palliative_care_unit', #'Unité des soins palliatifs', 
  '18N': 'inpatient_ward', 
  '13SM': 'high_dependency_unit', #'Unité 13 Sud -S.intermédiaires', 
  '09N': 'intensive_care', #'Unité des grands brûlés', 
  '12N': 'inpatient_ward', 
  '11NP': 'inpatient_ward', 
  '05CJ': 'day_surgery_unit',  #"Unité de chirurgie d'un jour (5 étage)", 
  '15SM': 'high_dependency_unit', #'Unité 15 Sud- S. intermédiaires', 
  '08NC': 'coronary_care_unit', #'Unité S.int. cardiaque', 
  '16N': 'inpatient_ward',  #'Unité 16 Nord', 
  'CCJO': 'day_surgery_unit', #'Chirurgie du même jour (O) Obstétrique', 
  '04CJ': 'day_surgery_unit',  #"Unité de chirurgie d'un jour (4 étage)", 
  'CELJ': 'inpatient_ward', # 'Équipe médecine (CELJ)'
  'CEC1': 'inpatient_ward', #'Équipe chirurgie (CEC1)',
  'CEC2': 'inpatient_ward', #'Équipe chirurgie (CEC2)',
  '09SB': 'inpatient_ward', #Unité des bébés dans chambre des mères'
  '09SN': 'inpatient_ward', #'Unité de néonatalogie', 
  '1HLR': 'inpatient_ward', #'Unité Hotel-Dieu - 1 LeRoyer'
  '2HLR': 'inpatient_ward', #'Unité Hotel-Dieu - 2 LeRoyer'
  '4HLR': 'inpatient_ward', #'Unité Hotel-Dieu - 4 LeRoyer',
  '5HDB': 'inpatient_ward', #'Unité Hotel-Dieu - 5 DeBullion',
  '5HLR': 'inpatient_ward', #'Unité Hotel-Dieu - 5 LeRoyer',
  '6HLR': 'inpatient_ward', #'Unité Hotel-Dieu - 6 LeRoyer',
  '6HDB': 'inpatient_ward', #'Unité Hotel-Dieu - 6 DeBullion',
  '7HDB': 'inpatient_ward', #'Unité Hotel-Dieu - 7 DeBullion',
}

#[
#  'prednisone',
#  'methylprednisolone *solu-medrol*',
#  'hydrocortisone *solu-cortef*'
#]

#[
#  'acide acetylsalicylique',
#  'ticagrelor',
#  'clopidogrel'
#]

#[
#  'rivaroxaban',
#  'apixaban',
#  'dabigatran'
#]

#[
#  'dalteparine',
#  'enoxaparine',
##  'heparine',
#  'tinzaparine'
#]

#[
#  'citalopram',
#  'escitalopram',
#  'paroxetine',
#  'fluoxetine',
#  'fluvoxamine',
#  'setraline',
#  'venlafaxine',
#  'desvenlafaxine',
#  'duloxetine'
#]

#[
##  'ramipril',
#  'perindopril',
#  'enalapril',
#  'captopril',
#  'irbesartan',
#  'losartan',
#  'olmesartan',
#  'valsartan'
#]

#[
#  'pregabaline',
#  'gabapentine'
#]

#[
#  'nifedipine',
#  'amlodipine'
#]

#[
#  'tamsulosine',
#  'alfuzosine'
#]
