from file_utils import read_csv

import pandas as pd
pd.set_option('display.max_rows', 250)

DEBUG = True

PATIENT_GLOBAL_SALT = '1fd5789d7ef4287fd8acfc765061e10eb3e7c093ff9150978695fb83692e4a87d55c4abf83c7ad9bcc3305ab03a4d28a5c404db6b84886c1665f949215e75a2b'
PATIENT_SITE_SALT = '243460170aec12b2cb4ce6e92d1293ebe8bbc83b4a860681ecfd4b653961f253fc3cb7ae833de5a4faca2d98ed9789e061e95aea7335901e6c84c7c05feee85f'
LIVE_SHEET_FILENAME = "/var/www/html/mchasse/covid19/data_all.csv"
CSV_DIRECTORY = "/data8/projets/Mila_covid19/output/covidb_full/csv"
BLOB_DIRECTORY = "/data8/projets/Mila_covid19/output/covidb_full/blob"
IMAGING_LIST_FILENAME = "/data8/projets/Mila_covid19/data/studies_to_extract.csv"
DICOM_MAP_FILENAME = "/data8/projets/Mila_covid19/data/patient_infos/dicom_id_map_v2.csv"
DICOM_DIRECTORY = "/data8/projets/Mila_covid19/data/covid_citadel_pacs_v1"
SQLITE_DIRECTORY = "/data8/projets/Mila_covid19/output/covidb_full/sqlite"
CODE_DIRECTORY = "/data8/projets/Mila_covid19/code/lmullie/git_Mila_covid19"

dicom_id_map_rows = read_csv(DICOM_MAP_FILENAME)
DICOM_PATIENT_ID_MAP = {}
DICOM_STUDY_ID_MAP = {}

for dicom_id_map_row in dicom_id_map_rows:
  if len(dicom_id_map_row) == 0: continue
  DICOM_PATIENT_ID_MAP[str(dicom_id_map_row[2])] = str(dicom_id_map_row[0])
  DICOM_STUDY_ID_MAP[str(dicom_id_map_row[2])] = str(dicom_id_map_row[1])

TABLE_COLUMNS = {

  'patient_data': [
    'patient_site_uid', 'patient_uid', 'pcr_sample_time', 
    'patient_site_code',
    'patient_covid_status', 'patient_age', 'patient_sex',
    'patient_death_status'
  ],

  'episode_data': [
    'patient_site_uid', 'episode_unit_type', 'episode_start_time', 
    'episode_end_time', 'episode_description',
  ],

  'diagnosis_data': [
    'patient_site_uid', 'diagnosis_type', 'diagnosis_time'
  ],

  'drug_data': [
    'patient_mrn', 'drug_name', 
    'drug_start_time', 'drug_end_time',
    'drug_frequency', 'drug_roa'
  ],

  'lab_data': [
    'patient_site_uid', 'lab_name', 'lab_sample_site', 'lab_sample_time',
    'lab_result_time', 'lab_result_status', 'lab_result_units',
    'lab_result_string', 'lab_result_value'
  ],

  'observation_data': [
    'patient_site_uid', 'observation_name', 'observation_time', 
    'observation_value', #'observation_units'
  ],

  'pcr_data': [
    'patient_site_uid', 'pcr_name', 'pcr_sample_site', 'pcr_sample_time', 
    'pcr_result_time', 'pcr_result_value'
  ],

  'culture_data': [
    'patient_site_uid', 'culture_type', 'culture_specimen_type', 'culture_sample_time', 
    'culture_result_time', 'culture_growth_positive'
  ],

  'imaging_data': [
    'patient_site_uid', 'imaging_accession_uid', 'imaging_modality', 'imaging_site'
  ],

  'slice_data': [
    'patient_site_uid', 'imaging_accession_uid', 'slice_study_instance_uid', 
    'slice_series_instance_uid', 'slice_data_uri', 'slice_view_position', 
    'slice_patient_position', 'slice_image_orientation', 'slice_image_position', 
    'slice_window_center', 'slice_window_width', 'slice_pixel_spacing', 
    'slice_thickness', 'slice_rows', 'slice_columns', 'slice_rescale_intercept', 
    'slice_rescale_slope'
  ]
}

DRUG_SKIP_VALUES = [
  '*** rx a domicile', 
  '*attention: patient anticoagulé*',
  'bilan comparatif des médicaments (bcm) au dossier.'
]

DRUG_ROUTE_MAP = {
  'sous-cutané': 'SC',
  'sous-cutané:': 'SC',
  'dans les oreilles': 'OTIC',
  'dans oreille droite': 'OTIC',
  'dans oreille gauche': 'OTIC',
  'ophthalmique': 'I-OCUL',
  'dans les yeux': 'I-OCUL',
  'dans l\'oeil droit': 'I-OCUL',
  'dans l\'oeil gauche': 'I-OCUL',
  'per os': 'PO',
  'per os ou sublingual': 'PO/SL',
  'via jéjunostomie': 'NG',
  'via gastrostomie': 'NG',
  'via tube nasogastro.': 'NG',
  'via levin': 'NG',
  'rince-bouche': 'BUCCAL',
  'en gargarisme': 'BUCCAL',
  'buccale': 'BUCCAL',
  'irr.nasale': 'NASAL',
  'dans une narine': 'NASAL',
  'dans les narines': 'NASAL',
  'nasale': 'NASAL',
  'infiltration': 'INFIL',
  'transdermique': 'T-DERMAL',
  'intra-dermique': 'I-DERMAL',
  'en injection locale': 'I-EPIDERMAL',
  'cathéter': 'IV',
  'i.v.': 'IV',
  'mini-perfuseur': 'IV',
  'i.v. perfusion': 'IV',
  'i.v. tubulure': 'IV',
  'i.v. soluté': 'IV',
  'i.v. / s.c.': 'IV/SC',
  'par voie centrale': 'IV',
  'i.m.': 'IM',
  'i.m./i.v./s.c.': 'IM/IV/SC',
  'i.m. / s.c.': 'IM/SC',
  'i.m. / i.v.': 'IM/IV',
  'perfusion s.c.': 'SC',
  'en appl. locale': 'TOPIC',
  'en compresses': 'TOPIC',
  'topique': 'TOPIC',
  'intra-rectal': 'RECTAL',
  'voir directives': 'UNKNOWN',
  'transdermale': 'T-DERMAL',
  'transmucosale': 'T-MUCOS',
  'épidurale': 'EPIDUR',
  'intra-rachidienne': 'I-SPINAL',
  'orale(s)': 'PO',
  'sublinguale': 'SL',
  'sous la langue': 'SL',
  'nébulisation orale': 'RESPIR',
  'en inhalation orale': 'RESPIR',
  'en aérosol': 'RESPIR',
  'vaginale': 'VAGIN',
  'dans le dialysat': 'HEMO',
}

LAB_CANCELLED_FLAGS = [
  'Test annulé', 'Test Annulé', 'ANN', 
  'ann', 'annulé', 'ANNULE', 'ANNULÉ',
  'test annulé', 'Annulé', 'ANNULe'
]

LAB_SKIP_VALUES = ['.', '..', '*00.0', '9*', '*9', 'Att. Hémolyse']

LAB_NAMES_MAP = {
  '% Éosino.Urin.': '% éosino.urin.', 
  '25(OH)-Vit. D': '25(oh)-vit. d', 
  'A-1-Antitryps. %': 'a-1-antitryps. %', 
  'A-1-Glycoprot. %': 'a-1-glycoprot. %', 
  'A-1-Glycoprot., Élec': 'a-1-glycoprot., élec', 
  'A.Foetoprotéine': 'a.foetoprotéine', 
  'A.lactique (rés.prélim.)': 'a.lactique (rés.prélim.)', 
  'A1 Antitrypsine': 'a1 antitrypsine', 
  'A1-Antitrypsine, Élec': 'a1-antitrypsine, élec', 
  'A2-Macroglob. %': 'a2-macroglob. %', 
  'A2-Macroglob., Élec': 'a2-macroglob., élec', 
  'ACTH': 'acth', 
  'ALT': 'alt', 
  'ARN VIH-1': 'arn vih-1', 
  'ARN VIH-1/Log': 'arn vih-1/log', 
  'AST': 'ast', 
  'Ac Fac.Intrins.': 'ac fac.intrins.', 
  'Ac. Valproïque': 'ac. valproïque', 
  'Acide Folique': 'acide folique', 
  'Acide Lac.Art. Ser.': 'acide lac.art. ser.', 
  'Acide Lactique': 'acide lactique', 
  'Acide Urique': 'acide urique', 
  'Acides Biliaires': 'acides biliaires', 
  'Act. Anti-Xa BPM': 'act. anti-xa bpm', 
  'Act. Anti-Xa Rivaro.': 'act. anti-xa rivaro.', 
  'Acétaminophène': 'acétaminophène', 
  'Ag Carcino Emb.': 'ag carcino emb.', 
  'Albumine': 'albumine', 
  'Albumine %': 'albumine %', 
  'Albumine, Liq.': 'albumine, liq.', 
  'Albumine, Urine': 'albumine, urine', 
  'Albumine, Élec.': 'albumine, élec.', 
  'Albumine-U 24 H': 'albumine-u 24 h', 
  'Albumine-U Mict.': 'albumine-u mict.', 
  'Ammoniac': 'ammoniac', 
  'Amylase, Liq.': 'amylase, liq.', 
  'Anti DNA Unité': 'anti dna unité', 
  'Anti Héparine': 'anti héparine', 
  'Anti JO-1': 'anti jo-1', 
  'Anti-CCP IgG': 'anti-ccp igg', 
  'Anti-HBs Unités': 'anti-hbs unités', 
  'Anti-HCV S/CO': 'anti-hcv s/co', 
  'Anti-Microsomiaux (Anti-TPO)': 'anti-microsomiaux (anti-tpo)', 
  'Anti-Récep.TSH': 'anti-récep.tsh', 
  'Anti-Thyroglobuline (Sér.)': 'anti-thyroglobuline (sér.)', 
  'Anti-Transglutaminase (IgA)': 'anti-transglutaminase (iga)', 
  'Anticardio.IgG': 'anticardio.igg', 
  'Anticardio.IgM': 'anticardio.igm', 
  'Anticorps Anti-GAD': 'anticorps anti-gad', 
  'Antigène Prost.': 'antigène prost.', 
  'B-hCG (Quant.)': 'b-hcg (quant.)', 
  'B2 Microglob.': 'b2 microglob.', 
  'B2-Glycopro.IgG': 'b2-glycopro.igg', 
  'Baso #': 'baso #', 
  'Baso # (Man)': 'baso # (man)', 
  'Benzo. (Urine)*': 'benzo. (urine)*', 
  'Benzo. Totales*': 'benzo. totales*', 
  'Bilirubine Dir.': 'bilirubine dir.', 
  'Bilirubine Ind.': 'bilirubine ind.', 
  'Bilirubine Tot.': 'bilirubine tot.', 
  'Bilirubine directe, liquide': 'bilirubine directe, liquide', 
  'Bilirubine, Liq.': 'bilirubine, liq.', 
  'Blaste # (Man)': 'blaste # (man)', 
  'C Télopeptide S': 'c télopeptide s', 
  'C-ANCA PR3 Val.': 'c-anca pr3 val.', 
  'C3': 'c3', 
  'C3/IgA': 'c3/iga', 
  'C3/IgA %': 'c3/iga %', 
  'C4': 'c4', 
  'CA 125': 'ca 125', 
  'CA 15-3': 'ca 15-3', 
  'CA 19-9': 'ca 19-9', 
  'CD16+56 Absolu': 'cd16+56 absolu', 
  'CD19 Absolu': 'cd19 absolu', 
  'CD3 Absolu': 'cd3 absolu', 
  'CD4 Absolu': 'cd4 absolu', 
  'CD8 Absolu': 'cd8 absolu', 
  'CENP-B': 'cenp-b', 
  'CGMH': 'cgmh', 
  'CK (AU)': 'ck (au)', 
  'CKMB masse': 'ckmb masse', 
  'CMV (Charge virale)': 'cmv (charge virale)', 
  'CMV IgG Unités': 'cmv igg unités', 
  'CMV IgM Index': 'cmv igm index', 
  'CO2 Total': 'co2 total', 
  'Ca Ion.(pH:7.4).': 'ca ion.(ph:7.4).', 
  'Ca Ionisé Act.': 'ca ionisé act.', 
  'Calcitonine': 'calcitonine', 
  'Calcium Total': 'calcium total', 
  'Calcium Total Corrigé': 'calcium total corrigé', 
  'Carbamazépine': 'carbamazépine', 
  'Carboxyhb Vein': 'carboxyhb vein', 
  'Chlorure': 'chlorure', 
  'Chlorure (LCR)': 'chlorure (lcr)', 
  'Chlorure veineux': 'chlorure veineux', 
  'Chlorure, Liq.': 'chlorure, liq.', 
  'Chlorure, Mict.': 'chlorure, mict.', 
  'Cholestérol': 'cholestérol', 
  'Cl Seringue': 'cl seringue', 
  'Cortisol (S)': 'cortisol (s)', 
  'Créatinine': 'créatinine', 
  'Créatinine 24 H': 'créatinine 24 h', 
  'Créatinine Urine': 'créatinine urine', 
  'Créatinine, Liq.': 'créatinine, liq.', 
  'Créatinine,Mict.': 'créatinine,mict.', 
  'Cyclo.2 H Post-D': 'cyclo.2 h post-d', 
  'Cyclos. Pré-Dose': 'cyclos. pré-dose', 
  'Céruloplasmine': 'céruloplasmine', 
  'D-Dimère': 'd-dimère', 
  'Digoxine': 'digoxine', 
  'Durée Gross. (Sem.)': 'durée gross. (sem.)', 
  'Décompte Cell.Tot. LBA': 'décompte cell.tot. lba', 
  'EBV-VCA IgM Ind': 'ebv-vca igm ind', 
  'Ebna1 IgG Index': 'ebna1 igg index', 
  'Excès de Base': 'excès de base', 
  'Excès de Base (V)': 'excès de base (v)', 
  'F.Rhumatoïde': 'f.rhumatoïde', 
  'FSH': 'fsh', 
  'Facteur II': 'facteur ii', 
  'Facteur V': 'facteur v', 
  'Facteur VII': 'facteur vii', 
  'Facteur VIII': 'facteur viii', 
  'Fer Sérique': 'fer sérique', 
  'Ferritine': 'ferritine', 
  'Fibrinogène': 'fibrinogène', 
  'Fibrinogène Imm.': 'fibrinogène imm.', 
  "G10_Sorgho d'Alep": "g10_sorgho d'alep", 
  'GB': 'gb', 
  'GGT': 'ggt', 
  'GR': 'gr', 
  'Gamma Glob. %': 'gamma glob. %', 
  'Gamma Globuline, Élec': 'gamma globuline, élec', 
  'Gap Anion.': 'gap anion.', 
  'Gl.Blancs L.Asc': 'gl.blancs l.asc', 
  'Gl.Blancs L.Bio': 'gl.blancs l.bio', 
  'Gl.Blancs L.Ple': 'gl.blancs l.ple', 
  'Gl.Blancs LCR': 'gl.blancs lcr', 
  'Gl.Rou. L.Bio': 'gl.rou. l.bio', 
  'Gl.Rou. LCR': 'gl.rou. lcr', 
  'Gl.Rou.L.Asc': 'gl.rou.l.asc', 
  'Globulines': 'globulines', 
  'Glucose': 'glucose', 
  'Glucose (LCR)': 'glucose (lcr)', 
  'Glucose AC': 'glucose ac', 
  'Glucose ADBD': 'glucose adbd', 
  'Glucose, Liq.': 'glucose, liq.', 
  'HBV DNA': 'hbv dna', 
  'HCO3 Actuel': 'hco3 actuel', 
  'HCO3 Actuel (V)': 'hco3 actuel (v)', 
  'HDL-Cholestérol': 'hdl-cholestérol', 
  'HSV-1 Index': 'hsv-1 index', 
  'HSV-2 Index': 'hsv-2 index', 
  'Haptoglobine': 'haptoglobine', 
  'Haptoglobine %': 'haptoglobine %', 
  'Haptoglobine, Élec.': 'haptoglobine, élec.', 
  'Hb': 'hb', 
  'Hb L.Bio': 'hb l.bio', 
  'IgA': 'iga', 
  'IgE': 'ige', 
  'IgG': 'igg', 
  'IgM': 'igm', 
  'Indice Alb/Créa': 'indice alb/créa', 
  'K Seringue': 'k seringue', 
  'K, Selles': 'k, selles', 
  'Kappa Libre': 'kappa libre', 
  'LD': 'ld', 
  'LD, Liq.': 'ld, liq.', 
  'LDL-C (Calc)': 'ldl-c (calc)', 
  'LH': 'lh', 
  'Lambda Libre': 'lambda libre', 
  'Lipase.': 'lipase.', 
  'Lympho #': 'lympho #', 
  'Lympho # (Man)': 'lympho # (man)', 
  'Lympho % LBA': 'lympho % lba', 
  'Magnésium': 'magnésium', 
  'Memb. Basale Glom.': 'memb. basale glom.', 
  'Mono #': 'mono #', 
  'Mono # (Man)': 'mono # (man)', 
  'Mono-Macro LBA': 'mono-macro lba', 
  'Myélocyte # (Man)': 'myélocyte # (man)', 
  'Métamyélocyte # (Man)': 'métamyélocyte # (man)', 
  'Métanéphrine Libre': 'métanéphrine libre', 
  'Méthémoglob Vein': 'méthémoglob vein', 
  'NT Pro-BNP': 'nt pro-bnp', 
  'Na Seringue': 'na seringue', 
  'Nb Cellules/mL': 'nb cellules/ml', 
  'Neutro #': 'neutro #', 
  'Neutro # (Man)': 'neutro # (man)', 
  'Neutro % LBA': 'neutro % lba', 
  'Non-HDL Cholest': 'non-hdl cholest', 
  'Normétanéphrine Libre': 'normétanéphrine libre', 
  'Osm.Calc.Selles': 'osm.calc.selles', 
  'Osmo. (Plasma)': 'osmo. (plasma)', 
  'Osmolalité Calculée': 'osmolalité calculée', 
  'Osmolalité Urine': 'osmolalité urine', 
  'Oxycodone qual. (mict.)': 'oxycodone qual. (mict.)', 
  'P-ANCA MPO Val.': 'p-anca mpo val.', 
  'PLT': 'plt', 
  'PLT sur Lame': 'plt sur lame', 
  'PTH Intacte': 'pth intacte', 
  'PTT-La': 'ptt-la', 
  'PTT-La (1:1)': 'ptt-la (1:1)', 
  'Parvo B19 IgG Index': 'parvo b19 igg index', 
  'Peptide-C': 'peptide-c', 
  'Phosphatase Alc.': 'phosphatase alc.', 
  'Phosphore': 'phosphore', 
  'Phénobarbital': 'phénobarbital', 
  'Phénytoïne': 'phénytoïne', 
  'Pic Mono. 1': 'pic mono. 1', 
  'Pic Mono. 1 %': 'pic mono. 1 %', 
  'Potassium': 'potassium', 
  'Potassium veineux': 'potassium veineux', 
  'Potassium, Mict.': 'potassium, mict.', 
  'Procalcitonine': 'procalcitonine', 
  'Prolactine': 'prolactine', 
  'Promyélocyte # (Man)': 'promyélocyte # (man)', 
  'Prot U/Créat U': 'prot u/créat u', 
  'Protéine C Réac.': 'protéine c réac.', 
  'Protéines (LCR)': 'protéines (lcr)', 
  'Protéines 24 H': 'protéines 24 h', 
  'Protéines Tot.Mict.': 'protéines tot.mict.', 
  'Protéines Totales': 'protéines totales', 
  'Protéines Urine': 'protéines urine', 
  'Protéines, Liq.': 'protéines, liq.', 
  'RNP': 'rnp', 
  'RVVT 1:1': 'rvvt 1:1', 
  'RVVT Confirme': 'rvvt confirme', 
  'RVVT Dépistage': 'rvvt dépistage', 
  'Rétic#': 'rétic#', 
  'SCL70': 'scl70', 
  'SHBG': 'shbg', 
  'SM': 'sm', 
  'SSA': 'ssa', 
  'SSB': 'ssb', 
  'Salicylates': 'salicylates', 
  'Sat O2 Art': 'sat o2 art', 
  'Sat O2 Vein': 'sat o2 vein', 
  'Sodium': 'sodium', 
  'Sodium veineux': 'sodium veineux', 
  'Sodium, Mict.': 'sodium, mict.', 
  'Sodium, Selles': 'sodium, selles', 
  'Stab # (Man)': 'stab # (man)', 
  'Staclot-La: Buffer': 'staclot-la: buffer', 
  'Staclot-La: Phospho': 'staclot-la: phospho', 
  'T.Céph.(1:1)': 't.céph.(1:1)', 
  'T.Céphaline Sec': 't.céphaline sec', 
  'T.Thrombine': 't.thrombine', 
  'T3 Libre': 't3 libre', 
  'T4 Libre': 't4 libre', 
  'TGMH': 'tgmh', 
  'TSH': 'tsh', 
  'Tacrolimus': 'tacrolimus', 
  'Température': 'température', 
  'Testostérone T': 'testostérone t', 
  'Thyroglobuline': 'thyroglobuline', 
  'Toxo IgM(Index)': 'toxo igm(index)', 
  'Toxoplasma IgG': 'toxoplasma igg', 
  'Transferrine': 'transferrine', 
  'Transferrine %': 'transferrine %', 
  'Transferrine, Élec.': 'transferrine, élec.', 
  'Transthyrétine': 'transthyrétine', 
  'Triglycérides': 'triglycérides', 
  'Triglycérides, Liq.': 'triglycérides, liq.', 
  'TropT Hs sous réserve': 'tropt hs sous réserve', 
  'Troponine-T HS': 'troponine-t hs', 
  'Urée': 'urée', 
  'Urée, Mict.': 'urée, mict.', 
  'VGM': 'vgm', 
  'VPM': 'vpm', 
  'VS': 'vs', 
  'Vanco Post Dose': 'vanco post dose', 
  'Vanco Pré Dose': 'vanco pré dose', 
  'Vancomycine': 'vancomycine', 
  'Vitamine A': 'vitamine a', 
  'Vitamine B12': 'vitamine b12', 
  'Vitamine E': 'vitamine e', 
  'Volume 24 Heures': 'volume 24 heures', 
  'Voriconazole': 'voriconazole', 
  'pCO2 TC': 'pco2 tc', 
  'pCO2 Veineux TC': 'pco2 veineux tc', 
  'pO2 TC': 'po2 tc', 
  'pO2 Veineux TC': 'po2 veineux tc', 
  'Éosino #': 'éosino #', 
  'Éosino # (Man)': 'éosino # (man)', 
  'Éosino LBA %': 'éosino lba %', 
  'Éthanol': 'éthanol'
  }

  